"""Closed reason-code taxonomy. Heads and engines MUST NOT emit free strings."""

# Classifier
REASON_FAST_PATH = "REASON_FAST_PATH"
REASON_AST_REJECTED = "REASON_AST_REJECTED"
REASON_REGIME_MARGIN = "REASON_REGIME_MARGIN"
REASON_REGIME_LOW_SCORE = "REASON_REGIME_LOW_SCORE"
REASON_REGIME_OVERRIDE = "REASON_REGIME_OVERRIDE"
REASON_NONSTANDARD_MATH = "REASON_NONSTANDARD_MATH"

# Selector
REASON_SELECTOR_FILL = "REASON_SELECTOR_FILL"
REASON_SELECTOR_OVERLAY = "REASON_SELECTOR_OVERLAY"
REASON_SELECTOR_INDEPENDENCE = "REASON_SELECTOR_INDEPENDENCE"
REASON_SELECTOR_FORCED = "REASON_SELECTOR_FORCED"

# Evidence
REASON_EVIDENCE_NUMERIC_MISMATCH = "REASON_EVIDENCE_NUMERIC_MISMATCH"
REASON_EVIDENCE_STALE = "REASON_EVIDENCE_STALE"
REASON_EVIDENCE_TEMPORAL = "REASON_EVIDENCE_TEMPORAL"
REASON_EVIDENCE_TRUST = "REASON_EVIDENCE_TRUST"
REASON_EVIDENCE_NEGATION = "REASON_EVIDENCE_NEGATION"

# Evaluator
REASON_UNCITED_CLAIM = "REASON_UNCITED_CLAIM"
REASON_POLARITY_MISMATCH = "REASON_POLARITY_MISMATCH"
REASON_UNAUTHORIZED_VETO = "REASON_UNAUTHORIZED_VETO"
REASON_MISSING_POLICY_RULES = "REASON_MISSING_POLICY_RULES"
REASON_MISSING_CAUSAL_GRAPH = "REASON_MISSING_CAUSAL_GRAPH"
REASON_MISSING_OBJECTIVE = "REASON_MISSING_OBJECTIVE"
REASON_UNBOUND_PATH = "REASON_UNBOUND_PATH"
REASON_POLICY_INCOMPLETE = "REASON_POLICY_INCOMPLETE"
REASON_CONSTRAINT_INCOMPLETE = "REASON_CONSTRAINT_INCOMPLETE"
REASON_UNSTRUCTURED_RULE_IGNORED = "REASON_UNSTRUCTURED_RULE_IGNORED"
REASON_DIVISION_BY_ZERO = "REASON_DIVISION_BY_ZERO"
REASON_LLM_INVALID = "REASON_LLM_INVALID"
REASON_TIMEOUT = "REASON_TIMEOUT"
REASON_CRASH = "REASON_CRASH"

# Contradiction
REASON_PAIR_BOTH_UNDETERMINED = "REASON_PAIR_BOTH_UNDETERMINED"
REASON_PAIR_UNDETERMINED_SKIPPED = "REASON_PAIR_UNDETERMINED_SKIPPED"
REASON_INVERTED_EVIDENCE = "REASON_INVERTED_EVIDENCE"
REASON_INVERTED_CONSTRAINT = "REASON_INVERTED_CONSTRAINT"
REASON_ASSUMPTION_FLIP = "REASON_ASSUMPTION_FLIP"

# Counterfactual
REASON_COUNTERFACTUAL_NO_SCHEMA = "REASON_COUNTERFACTUAL_NO_SCHEMA"
REASON_COUNTERFACTUAL_BUDGET = "REASON_COUNTERFACTUAL_BUDGET"
REASON_COUNTERFACTUAL_RESOLVED = "REASON_COUNTERFACTUAL_RESOLVED"

# Lattice / review
REASON_REVIEW_VETO = "REASON_REVIEW_VETO"
REASON_REVIEW_CONFLICT = "REASON_REVIEW_CONFLICT"
REASON_REVIEW_UNCERTAINTY = "REASON_REVIEW_UNCERTAINTY"
REASON_REVIEW_EVIDENCE = "REASON_REVIEW_EVIDENCE"
REASON_ELIGIBILITY_GATE = "REASON_ELIGIBILITY_GATE"
REASON_REVIEW_POLICY_CAUTION = "REASON_REVIEW_POLICY_CAUTION"

REVIEW_TRIGGERS = frozenset(
    {
        REASON_UNAUTHORIZED_VETO,
        REASON_LLM_INVALID,
        REASON_POLICY_INCOMPLETE,
        REASON_CONSTRAINT_INCOMPLETE,
        REASON_SELECTOR_INDEPENDENCE,
    }
)

ALL_REASON_CODES = frozenset(
    v for k, v in globals().items() if k.startswith("REASON_")
)
